CREATE TABLE "Artist" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT
);

CREATE TABLE Genre (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	name TEXT
);

CREATE TABLE Album (
	id		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	artist_id	INTEGER,
	title		TEXT
);

CREATE TABLE Track (
	id		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	title TEXT,
	album_id INTEGER,
	genre_id INTEGER,
	len INTEGER, rating INTEGER, count INTEGER
);
